INSERT INTO cart (cart_no, CART_QTY, CART_TOT_PRICE, CART_PRODUCT_SIZE, CART_PRODUCT_COLOR, MEMBER_ID, PRODUCT_NO) 
VALUES (cart_cart_no_SEQ.nextval, 2, 59800, 'M', 'Black', 'uni1', 431976);

INSERT INTO cart (cart_no, CART_QTY, CART_TOT_PRICE, CART_PRODUCT_SIZE, CART_PRODUCT_COLOR, MEMBER_ID, PRODUCT_NO) 
VALUES (cart_cart_no_SEQ.nextval, 1, 39900, 'M', 'Gray', 'uni1', 433113);

INSERT INTO cart (cart_no, CART_QTY, CART_TOT_PRICE, CART_PRODUCT_SIZE, CART_PRODUCT_COLOR, MEMBER_ID, PRODUCT_NO) 
VALUES (cart_cart_no_SEQ.nextval, 1, 39900, 'M', 'Blue', 'uni1', 418873);

INSERT INTO cart (cart_no, CART_QTY, CART_TOT_PRICE, CART_PRODUCT_SIZE, CART_PRODUCT_COLOR, MEMBER_ID, PRODUCT_NO) 
VALUES (cart_cart_no_SEQ.nextval, 3, 299700, 'S', 'Green', 'uni2', 428866);

INSERT INTO cart (cart_no, CART_QTY, CART_TOT_PRICE, CART_PRODUCT_SIZE, CART_PRODUCT_COLOR, MEMBER_ID, PRODUCT_NO) 
VALUES (cart_cart_no_SEQ.nextval, 1, 59900, 'M', 'Yellow', 'uni3', 435455);

commit;