INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, 'IDLF트위스트플리츠롱스커트', 'M', 'Blue', 39900, 1, 1, 433113);

INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, '보아후리스크루넥가디건(긴팔)', 'M', 'Red', 39900, 1, 1, 429667);

INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, 'IDLF3D니트자카드스웨터(긴팔)', 'S', 'White', 49900, 1, 2, 432087);

INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, '울트라스트레치진20FW', 'S', 'Blue', 49900, 1, 2, 429094);

INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, '플란넬체크셔츠(긴팔)', 'L', 'White', 29900, 1, 3, 432614);

INSERT INTO jumun_detail (JUMUN_D_NO, JUMUN_D_PRODUCT_NAME, JUMUN_D_PRODUCT_SIZE, JUMUN_D_PRODUCT_COLOR, JUMUN_D_PRODUCT_PRICE, JUMUN_D_PRODUCT_QTY, JUMUN_NO, PRODUCT_NO) 
VALUES (jumun_detail_jumun_d_no_SEQ.nextval, 'U크루넥T(긴팔)20SS', 'L', 'Black', 29900, 1, 3, 425213);

commit;